
// Setting up dependencies
const express = require("express");
const router = express.Router();

// Import the model (burger.js) to use its database functions.
const Burger = require("../models/burger.js");

// Routes- 


//This will get all the burgers using the selectall burger controller, package the burger into 'hbs object' and then send it to the handle bars
router.get("/", function(req, res) {
  Burger.selectAll(function(data) {
    var hbsObject = {
      burgers: data
    };
    console.log(hbsObject);
    res.render("index", hbsObject);
  });
});

// Post request to receive burger_name and devoured status from the ajax request generated by the HTML click events and forminput, using req.body
// Executing the MYSQL query update the burgers column and the devoured column 
// This is only 

router.post("/api/burgers", function(req, res) {
    Burger.insertOne([
      "burger_name", "devoured"
    ], [
      req.body.burger_name, req.body.devoured
    ], function(result) {
      // Checking to see if a unique id has been assigned
      res.json({ id: result.insertId });
    });
  });